### ISSUE TITLE
Suggestions about improvment

### ISSUE THREAD

**Issue by minanagehsalalma** [n3rada/Rainbox#1]
Why don't you look at the password pattern like this instead ?

https://quentinkaiser.be/security/2021/03/09/voodoo/

https://deadcode.me/blog/2016/07/01/UPC-UBEE-EVW3226-WPA2-Reversing.html

**Comment by n3rada** [comment]
Hey !
I didn't even know this kind of thing. 
I started to try to learn about this from bottom. 
Thanks for taking your time to give me these links!
I'm going to delete the project and think in my own time.

**Comment by n3rada** [comment]
Hi!

Thanks for taking your time to provide me with these links.
Nevertheless, this is not at all the same case as me. 

I don't have the same approach nor the same possibility (I can't afford to open the manufacturers routers of the big French operators).  Here, I can only rely on the passwords "visually" and try to shape the generator according to that!

So to say that it is "useless" is wrong. It's interesting in terms of generation possibility actually it's better than using crunch.

If you have an idea, I'm interested.

Best Regards,

**Comment by minanagehsalalma** [comment]
> I can't afford to open the manufacturers routers of the big French operators

@n3rada there is no need for that you can just search the router name plus the word firmware and you will surely find it posted in some forums. .. and also you can grab the firmware files using ssh or ftp from the device in somecases

> So to say that it is "useless" is wrong. It's interesting in terms of generation possibility actually it's better than using crunch.

I said that because you would need a super computer to crack such passwords!

**Comment by n3rada** [comment]
If I give you the information that the router is a "thomson tg787", can you give me the wpa2 key generation algorithm? My curiosity is all yours and I'd love to hear from you!

Nevertheless, my goal here is to create a tool for educational and demonstrative purposes. It's all about luck. I tried it with a friend's basic router code and it worked (the key was "oWDduULh0xGjPTsBjY" and it was found on the 234th line of the generated file) !

In fact, the real goal would be that we could each continue to increase a wordlist file on a remote server with this tool, by having our machines work separately and that with each update, the file grows larger and larger until it fills most cases.

In my experience, I prefer to use my tool for router security testing than a good old crunch.

**Comment by minanagehsalalma** [comment]
> If I give you the information that the router is a "thomson tg787", can you give me the wpa2 key generation algorithm?

Well, first try to grab the exact router firmware as the generation algorithm changes by isp.

Second try to apply the articles steps on it.

Also try to search the router model + password generator.

Anyway i don't have enough experience in reverse engineering to pull something like this out.

**Comment by minanagehsalalma** [comment]
> I tried it with a friend's basic router code and it worked (the key was "oWDduULh0xGjPTsBjY" and it was found on the 234th line of the generated file) !

Well that doesn't make sense at all.

**Comment by n3rada** [comment]
> > I tried it with a friend's basic router code and it worked (the key was "oWDduULh0xGjPTsBjY" and it was found on the 234th line of the generated file) !
> 
> Well that doesn't make sense at all.

What unfortunately does not make sense is your way of arguing in response. Explain to me how? Have you read the README.md?

**Comment by n3rada** [comment]
> > If I give you the information that the router is a "thomson tg787", can you give me the wpa2 key generation algorithm?
> 
> Well, first try to grab the exact router firmware as the generation algorithm changes by isp.
> 
> Second try to apply the articles steps on it.
>  I have read the article but I am dealing here with ALL the routers of the major French operators. The aim is to make it easier to find passwords by just having remote access to the router. 

Moreover, the article deals with a specific and outdated router!

**Comment by minanagehsalalma** [comment]
> What unfortunately does not make sense is your way of arguing in response. Explain to me how? Have you read the README.md?

the part that it was able to find it in the 234th line That can't be possible ?!

> Moreover, the article deals with a specific and outdated router!

nope if you were able to understand the points discussed there , you can apply these steps again on the most of the routers !
[check this new video](https://youtu.be/3yP3QOT-h98?t=603)

> The aim is to make it easier to find passwords by just having remote access to the router

by doing what ? mate you need to work on your English i can't guess what you mean every sentence.

**Comment by n3rada** [comment]
> > What unfortunately does not make sense is your way of arguing in response. Explain to me how? Have you read the README.md?
> 
> the part that it was able to find it in the 234th line That can't be possible ?!

Yes it can ! I'll update the README.md with an example later, thus you'll be able to understand better i think !

> > Moreover, the article deals with a specific and outdated router!
> 
> nope if you were able to understand the points discussed there , you can apply these steps again on the most of the routers !
> [check this new video](https://youtu.be/3yP3QOT-h98?t=603)

Hm. Maybe I missed something. To not lie to you, I'm running out lot of others things at this time so I looked quickly these links. This Italian man's seems to be very interesting. I saved it for another free time. Thanks.

> > The aim is to make it easier to find passwords by just having remote access to the router
> 
> by doing what ? mate you need to work on your English i can't guess what you mean every sentence.

Don't be condescending. I think it's not my English that is the primary cause here but your understanding. I've already explained over and over again that this is not a reverse engineering tool (as I've never studied that branch of the field) but an improvement in the brute force probability of keys.

**Comment by n3rada** [comment]
You seem to be very interested in this subject. Do not hesitate to contact me privately if you wish to discuss it more specifically or to work together.

Best Regards

**Comment by minanagehsalalma** [comment]
> I've already explained over and over again that this is not a reverse engineering tool (as I've never studied that branch of the field) but an improvement in the brute force probability of keys.

yeah i know , i was just suggesting that this would be a better method.

> Do not hesitate to contact me privately if you wish to discuss it more specifically or to work together.

maybe later , thanks for the offer.
